seq= input("Please introduce a DNA sequence: ")
a_count = seq.count("A")
g_count = seq.count("G")
c_count = seq.count("C")
t_count = seq.count("T")
print("Total length:",len(seq))
print("A:", a_count)
print("C:", c_count)
print("G:", g_count)
print("T:", t_count)
